#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 19 10:34:49 2018

@author: yiqian
"""

# Write your MySQL query statement below
SELECT Person.FirstName, Person.LastName, Address.City, Address.State 
from Person LEFT JOIN Address on Person.PersonId = Address.PersonId;

