#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun 21 17:21:36 2018

@author: yiqian
"""

# Write your MySQL query statement below
select name, population, area
from World
where area > 3000000 or population>25000000